spring.application.name=villadictos-app

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/villadictos_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=villadictos
spring.datasource.password=villadictos123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SQL Initialization
spring.sql.init.mode=always
